[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "easy-django"
version = "0.1.0"
description = "Modular Django boilerplate"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}
authors = [
  {name = "Sivakumar, Selva", email = "techsiva33@gmail.com"},
]
dependencies = [
  "Django>=3.2",
  "djangorestframework>=3.14"
]

[project]
name = "easy-django"
version = "0.0.1"
authors = [
  { name="Sivakumar, Selva", email="skr.iitg@gmail.com" },
]
description = "Modular Django boilerplate"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/skrindra/easy-django"
Issues = "https://github.com/skrindra/easy-django/issues"
